#!/usr/bin/env bun
/**
 * Reads packages/client/dist/ and generates a TypeScript module
 * that embeds all files as base64 strings with their MIME types.
 * The output is imported by the server at compile time.
 */
import { readdirSync, statSync, readFileSync, writeFileSync } from "fs";
import { join, relative, extname } from "path";

const CLIENT_DIST = join(import.meta.dir, "..", "packages", "client", "dist");
const OUT = join(import.meta.dir, "..", "packages", "server", "src", "embedded-assets.ts");

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".svg": "image/svg+xml",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".ttf": "font/ttf",
};

function walk(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...walk(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

const files = walk(CLIENT_DIST);
const entries: string[] = [];
let totalBytes = 0;

for (const file of files) {
  const rel = "/" + relative(CLIENT_DIST, file).replace(/\\/g, "/");
  const ext = extname(file);
  const mime = MIME[ext] ?? "application/octet-stream";
  const data = readFileSync(file);
  totalBytes += data.length;
  const b64 = data.toString("base64");
  entries.push(`  ${JSON.stringify(rel)}: { data: ${JSON.stringify(b64)}, type: ${JSON.stringify(mime)} }`);
}

const code = `// Auto-generated by scripts/embed-client.ts — do not edit
// ${files.length} files, ${(totalBytes / 1024).toFixed(0)} KB total

const _raw: Record<string, { data: string; type: string }> = {
${entries.join(",\n")}
};

function decode(b64: string): Uint8Array {
  return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
}

const cache = new Map<string, Uint8Array>();

export function getAsset(path: string): { body: Uint8Array; type: string } | null {
  const entry = _raw[path];
  if (!entry) return null;
  let body = cache.get(path);
  if (!body) {
    body = decode(entry.data);
    cache.set(path, body);
  }
  return { body, type: entry.type };
}

export const hasEmbeddedAssets = true;
`;

writeFileSync(OUT, code);
console.log(`  Embedded ${files.length} files (${(totalBytes / 1024).toFixed(0)} KB) → embedded-assets.ts`);
